import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,client,otherHeaders,ownerHeaders} from './support.mjs';
import {createAssembly,emptyGraph,id,makePiece} from '../lib/world.ts';
import {grantFunds,refundOperation} from '../server/wallet.ts';
async function setup(){const f=fixture();assert.equal((await client(f,'/api/bootstrap')).status,200);const r=await client(f,'/api/projects','POST',{name:'Integration project',kind:'blank'});assert.equal(r.status,201);return{...f,p:r.body};}
async function quote(f,g=createAssembly('application')){const r=await client(f,`/api/projects/${f.p.id}/quote`,'POST',{graph:g,revision:f.p.revision});assert.equal(r.status,200,JSON.stringify(r.body));return r.body}
async function apply(f,q){return client(f,'/api/quotes/apply','POST',{quoteId:q.id,requestId:id()})}
test('unauthenticated access is rejected and startup has exactly three inactive plans',async()=>{const f=fixture();try{assert.equal((await client(f,'/api/bootstrap','GET',undefined,{})).status,401);const r=await client(f,'/api/bootstrap');assert.equal(r.body.wallet.plans.length,3);assert.ok(r.body.wallet.plans.every(p=>!p.active));assert.equal(r.body.wallet.total,0);assert.equal(r.body.user.admin,true);assert.equal(r.body.user.name,'Workshop Owner')}finally{f.close()}});
test('test funding is one-time even with concurrent retries and never touches live funds',async()=>{const f=await setup();try{await Promise.all(Array.from({length:6},()=>client(f,'/api/wallet/test-grant','POST',{})));const w=(await client(f,'/api/wallet')).body;assert.equal(w.total,100000000);assert.equal(w.ledger.length,1);assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM wallets WHERE mode='live'").get().n,0)}finally{f.close()}});
test('apply and debit are atomic, replay-safe and consume subscription dollars first',async()=>{const f=await setup();try{await grantFunds(f.env,'owner-id','test',20000,'subscription','fixture:subscription','Included balance');await grantFunds(f.env,'owner-id','test',1000000,'topup','fixture:topup','Purchased balance');const q=await quote(f);const results=await Promise.all([apply(f,q),apply(f,q),apply(f,q)]);assert.ok(results.every(r=>r.status===200),JSON.stringify(results));const w=(await client(f,'/api/wallet')).body;assert.equal(w.total,1020000-q.amount);assert.equal(w.subscription,0);assert.equal(w.ledger.filter(e=>e.kind==='usage').length,1);const p=(await client(f,`/api/projects/${f.p.id}`)).body;assert.equal(p.revision,1);assert.equal(p.snapshots.length,1);assert.equal(p.graph.pieces.length,createAssembly('application').pieces.length);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM operations').get().n,1)}finally{f.close()}});
test('insufficient funds do not mutate graph, ledger or quote',async()=>{const f=await setup();try{const q=await quote(f),result=await apply(f,q);assert.equal(result.status,409);assert.equal(f.sqlite.prepare('SELECT revision FROM projects WHERE id=?').get(f.p.id).revision,0);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM ledger').get().n,0);assert.equal(f.sqlite.prepare('SELECT used FROM quotes WHERE id=?').get(q.id).used,0)}finally{f.close()}});
test('expired, stale, or mode-mismatched quotes cannot debit',async()=>{const f=await setup();try{await client(f,'/api/wallet/test-grant','POST',{});const q=await quote(f);f.sqlite.prepare('UPDATE quotes SET expires_at=? WHERE id=?').run(Date.now()-1000,q.id);assert.equal((await apply(f,q)).status,409);const q2=await quote(f);f.env.BILLING_MODE='live';assert.equal((await apply(f,q2)).status,409);f.env.BILLING_MODE='test';const q3=await quote(f);f.sqlite.prepare('UPDATE projects SET revision=revision+1 WHERE id=?').run(f.p.id);assert.equal((await apply(f,q3)).status,409);assert.equal((await client(f,'/api/wallet')).body.total,100000000)}finally{f.close()}});
test('draft compare-and-swap prevents overwritten edits; newer draft invalidates quotes',async()=>{const f=await setup();try{await client(f,'/api/wallet/test-grant','POST',{});const q=await quote(f),g=createAssembly('application');const save=await client(f,`/api/projects/${f.p.id}`,'PATCH',{draft:g,revision:0,draftRevision:0});assert.equal(save.status,200);assert.equal((await client(f,`/api/projects/${f.p.id}`,'PATCH',{draft:emptyGraph(),revision:0,draftRevision:0})).status,409);assert.equal((await apply(f,q)).status,409);assert.equal((await client(f,'/api/wallet')).body.total,100000000)}finally{f.close()}});
test('cross-project access, viewer edits, billing settings and token privilege escalation are rejected',async()=>{const f=await setup();try{await client(f,'/api/bootstrap','GET',undefined,otherHeaders);assert.equal((await client(f,`/api/projects/${f.p.id}`,'GET',undefined,otherHeaders)).status,404);await client(f,`/api/projects/${f.p.id}/members`,'POST',{email:'other@example.test',role:'viewer'});assert.equal((await client(f,`/api/projects/${f.p.id}`,'GET',undefined,otherHeaders)).status,200);assert.equal((await client(f,`/api/projects/${f.p.id}`,'PATCH',{draft:emptyGraph(),revision:0,draftRevision:0},otherHeaders)).status,403);assert.equal((await client(f,'/api/admin/settings','GET',undefined,otherHeaders)).status,403);const token=(await client(f,`/api/projects/${f.p.id}/tokens`,'POST',{name:'Reader',scopes:['read'],maxCharge:0})).body.token;assert.ok(token.startsWith('vw_'));assert.equal((await client(f,`/api/projects/${f.p.id}/quote`,'POST',{graph:createAssembly('application'),revision:0},{authorization:'Bearer '+token})).status,403);assert.equal((await client(f,'/api/wallet','GET',undefined,{authorization:'Bearer '+token})).status,403)}finally{f.close()}});
test('CSRF protection rejects foreign browser origins',async()=>{const f=await setup();try{assert.equal((await client(f,'/api/wallet/test-grant','POST',{}, {...ownerHeaders,origin:'https://evil.test'})).status,403);assert.equal((await client(f,'/api/wallet/test-grant','POST',{}, {...ownerHeaders,'sec-fetch-site':'cross-site'})).status,403)}finally{f.close()}});
test('import is free into new projects and cannot replace an established revision',async()=>{const f=await setup();try{const r=await client(f,`/api/projects/${f.p.id}/import`,'POST',{graph:createAssembly('application')});assert.equal(r.status,200);assert.equal((await client(f,'/api/wallet')).body.total,0);assert.equal((await client(f,`/api/projects/${f.p.id}/import`,'POST',{graph:emptyGraph()})).status,409);const p=(await client(f,`/api/projects/${f.p.id}`)).body;assert.equal(p.snapshots.length,1);assert.equal(p.revision,1)}finally{f.close()}});
test('deletions can be applied with no wallet funds',async()=>{const f=await setup();try{await client(f,`/api/projects/${f.p.id}/import`,'POST',{graph:createAssembly('application')});f.p.revision=1;const q=await quote(f,emptyGraph());assert.equal(q.amount,0);assert.equal((await apply(f,q)).status,200);assert.equal((await client(f,`/api/projects/${f.p.id}`)).body.graph.pieces.length,0)}finally{f.close()}});
test('refund is one-time, returns the original buckets, and preserves completed operations',async()=>{const f=await setup();try{await grantFunds(f.env,'owner-id','test',40000,'subscription','fixture:sub','Subscription');await grantFunds(f.env,'owner-id','test',1000000,'topup','fixture:top','Topup');const q=await quote(f),r=await apply(f,q),op=r.body.operation;await refundOperation(f.env,op.id,'Should not refund a completed operation');assert.equal((await client(f,'/api/wallet')).body.total,1040000-q.amount);f.sqlite.prepare("UPDATE operations SET status='running' WHERE id=?").run(op.id);await Promise.all([refundOperation(f.env,op.id,'Provider failed'),refundOperation(f.env,op.id,'Provider failed')]);const w=(await client(f,'/api/wallet')).body;assert.equal(w.subscription,40000);assert.equal(w.topup,1000000);assert.equal(w.ledger.filter(e=>e.kind==='refund').length,1)}finally{f.close()}});
test('repeated payment event IDs grant once',async()=>{const f=await setup();try{await Promise.all([grantFunds(f.env,'owner-id','test',123000000,'subscription','stripe:invoice:test','Monthly'),grantFunds(f.env,'owner-id','test',123000000,'subscription','stripe:invoice:test','Monthly')]);assert.equal((await client(f,'/api/wallet')).body.total,123000000)}finally{f.close()}});
test('real checkout stays blocked while billing is unconfigured',async()=>{const f=await setup();try{const r=await client(f,'/api/payments/checkout','POST',{kind:'topup',amountCents:2500,requestId:id()});assert.equal(r.status,409);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM checkouts').get().n,0)}finally{f.close()}});
test('private publications require membership and validate/idempotently save forms',async()=>{const f=await setup();try{const g=createAssembly('application'),form=makePiece('form',g.pieces[0].id),input=makePiece('input',form.id);g.pieces.push(form,input);await client(f,`/api/projects/${f.p.id}/import`,'POST',{graph:g});const pub=(await client(f,`/api/projects/${f.p.id}/publish`,'POST',{})).body;assert.ok(pub.id);assert.equal((await client(f,pub.url)).status,200);assert.equal((await client(f,pub.url,'GET',undefined,otherHeaders)).status,404);assert.equal((await client(f,pub.url+'/submit','POST',{pieceId:form.id,data:{email:'invalid'},requestId:id()})).status,400);const response={pieceId:form.id,data:{email:'hello@example.test'},requestId:id()};assert.equal((await client(f,pub.url+'/submit','POST',response)).status,200);assert.equal((await client(f,pub.url+'/submit','POST',response)).status,200);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM submissions').get().n,1);await client(f,`/api/projects/${f.p.id}/publications/${pub.id}`,'DELETE');assert.equal((await client(f,pub.url)).status,404)}finally{f.close()}});
test('original asset upload/download is private, free, and rejects active document types',async()=>{const f=await setup();try{const data=new FormData();data.set('file',new File([new Uint8Array([137,80,78,71])],'image.png',{type:'image/png'}));const r=await client(f,`/api/projects/${f.p.id}/assets`,'POST',data);assert.equal(r.status,201);assert.equal((await client(f,r.body.url)).status,200);assert.equal((await client(f,r.body.url,'GET',undefined,otherHeaders)).status,404);const bad=new FormData();bad.set('file',new File(['<svg onload="alert(1)">'],'bad.svg',{type:'image/svg+xml'}));assert.equal((await client(f,`/api/projects/${f.p.id}/assets`,'POST',bad)).status,400);assert.equal((await client(f,'/api/wallet')).body.total,0)}finally{f.close()}});
test('transaction failure rolls back graph, wallet, operation and ledger',async()=>{const f=await setup();try{await client(f,'/api/wallet/test-grant','POST',{});const q=await quote(f);f.sqlite.exec("CREATE TRIGGER fail_snapshot BEFORE INSERT ON snapshots BEGIN SELECT RAISE(ABORT, 'fixture failure'); END");assert.equal((await apply(f,q)).status,500);assert.equal((await client(f,'/api/wallet')).body.total,100000000);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM operations').get().n,0);assert.equal(f.sqlite.prepare('SELECT revision FROM projects WHERE id=?').get(f.p.id).revision,0)}finally{f.close()}});
test('media byte ranges allow seeking while retaining project access checks',async()=>{const f=await setup();try{const form=new FormData();form.set('file',new File(['0123456789'],'clip.webm',{type:'video/webm'}));const asset=(await client(f,`/api/projects/${f.p.id}/assets`,'POST',form)).body;const r=await client(f,asset.url,'GET',undefined,{...ownerHeaders,range:'bytes=3-6'});assert.equal(r.status,206);assert.equal(r.body,'3456');assert.equal(r.headers.get('content-range'),'bytes 3-6/10');assert.equal((await client(f,asset.url,'GET',undefined,{...ownerHeaders,range:'bytes=99-100'})).status,416);assert.equal((await client(f,asset.url,'GET',undefined,{...otherHeaders,range:'bytes=3-6'})).status,404)}finally{f.close()}});
