import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,client,ownerHeaders} from './support.mjs';
import {id} from '../lib/world.ts';
import {draftPlans,testTariffs} from '../lib/money.ts';
async function signed(f,event){const raw=JSON.stringify(event),t=Math.floor(Date.now()/1000),secret=f.env.STRIPE_WEBHOOK_SECRET,key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(t+'.'+raw))).toString('hex');return client(f,'/api/payments/webhook','POST',event,{'stripe-signature':`t=${t},v1=${sig}`});}
async function setup(){const f=fixture();f.env.BILLING_MODE='live';f.env.STRIPE_SECRET_KEY='sk_live_local_fixture_not_a_real_key';f.env.STRIPE_WEBHOOK_SECRET='whsec_local_fixture';await client(f,'/api/bootstrap');await client(f,'/api/admin/settings','PUT',{plans:draftPlans.map(p=>({...p,monthlyMicros:50000000,grantMicros:100000000,active:true,stripePriceId:'price_'+p.id})),tariffs:{...testTariffs,approved:true}});return f;}
test('signed top-up events grant only the paid approved amount, once per session',async()=>{const f=await setup(),fetchOriginal=globalThis.fetch;try{globalThis.fetch=async(url,init)=>{assert.ok(String(url).startsWith('https://api.stripe.com/v1/checkout/sessions'));return Response.json({id:'cs_fixture',url:'https://checkout.stripe.com/c/pay/fixture'})};const requestId=id(),checkoutId='owner-id:'+requestId;const checkout=await client(f,'/api/payments/checkout','POST',{kind:'topup',amountCents:2500,requestId});assert.equal(checkout.status,200);const obj={id:'cs_fixture',metadata:{checkout_id:checkoutId},mode:'payment',payment_status:'paid',currency:'usd',amount_total:2500};const event={id:'evt_1',type:'checkout.session.completed',livemode:true,data:{object:obj}};assert.equal((await signed(f,event)).status,200);assert.equal((await signed(f,event)).status,200);assert.equal((await signed(f,{...event,id:'evt_2',type:'checkout.session.async_payment_succeeded'})).status,200);const w=(await client(f,'/api/wallet')).body;assert.equal(w.topup,25000000);assert.equal(w.ledger.length,1);assert.equal((await signed(f,{...event,id:'evt_tampered',data:{object:{...obj,amount_total:5000}}})).status,400);assert.equal((await client(f,'/api/wallet')).body.topup,25000000)}finally{globalThis.fetch=fetchOriginal;f.close()}});
test('subscription checkout does not grant; each paid monthly invoice grants once',async()=>{const f=await setup(),fetchOriginal=globalThis.fetch;try{const requestId=id(),checkoutId='owner-id:'+requestId;globalThis.fetch=async(url,init)=>{const path=String(url);if(path.includes('/prices/'))return Response.json({active:true,currency:'usd',unit_amount:5000,recurring:{interval:'month',interval_count:1}});if(path.includes('/subscriptions/'))return Response.json({id:'sub_fixture',metadata:{checkout_id:checkoutId},status:'active',customer:'cus_fixture'});if(path.endsWith('/checkout/sessions'))return Response.json({id:'cs_sub_fixture',url:'https://checkout.stripe.com/c/pay/subfixture'});throw Error('Unexpected provider request')};assert.equal((await client(f,'/api/payments/checkout','POST',{kind:'subscription',planId:'pro',requestId})).status,200);assert.equal((await client(f,'/api/payments/checkout','POST',{kind:'subscription',planId:'pro',requestId:id()})).status,409);assert.equal((await signed(f,{id:'evt_checkout',type:'checkout.session.completed',livemode:true,data:{object:{id:'cs_sub_fixture',mode:'subscription',payment_status:'paid',metadata:{checkout_id:checkoutId}}}})).status,200);assert.equal((await client(f,'/api/wallet')).body.total,0);const invoice={id:'in_1',subscription:'sub_fixture',currency:'usd',status:'paid',amount_paid:5000,billing_reason:'subscription_create'};const evt={id:'evt_invoice_1',type:'invoice.paid',livemode:true,data:{object:invoice}};assert.equal((await signed(f,evt)).status,200);assert.equal((await signed(f,{...evt,id:'evt_invoice_duplicate'})).status,200);assert.equal((await client(f,'/api/wallet')).body.subscription,100000000);assert.equal((await signed(f,{...evt,id:'evt_proration',data:{object:{...invoice,id:'in_proration',billing_reason:'subscription_update'}}})).status,200);assert.equal((await client(f,'/api/wallet')).body.subscription,100000000);assert.equal((await signed(f,{...evt,id:'evt_renewal',data:{object:{...invoice,id:'in_2',billing_reason:'subscription_cycle'}}})).status,200);assert.equal((await client(f,'/api/wallet')).body.subscription,200000000)}finally{globalThis.fetch=fetchOriginal;f.close()}});
test('unsigned webhooks and test-mode events cannot credit live wallets',async()=>{const f=await setup();try{assert.equal((await client(f,'/api/payments/webhook','POST',{id:'evt_fake',livemode:true})).status,400);assert.equal((await signed(f,{id:'evt_test',type:'checkout.session.completed',livemode:false,data:{object:{}}})).status,200);assert.equal((await client(f,'/api/wallet')).body.total,0)}finally{f.close()}});
