import {readFileSync,writeFileSync,mkdirSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {emptyGraph,makePiece} from '../lib/world.ts';
import {portableFiles} from '../lib/portable.ts';
const source=name=>readFileSync(new URL('../'+name,import.meta.url),'utf8');
export const sources={world:source('lib/world.ts'),compiler:source('lib/compiler.ts'),forms:source('lib/forms.ts'),projectIo:source('lib/project-io.ts'),...Object.fromEntries(['build','server','responses','instance'].map(k=>[k,source('portable/'+k+'.mjs.template')])),adminAuth:source('portable/admin-auth.mjs.template'),adminOperator:source('portable/admin-operator.mjs.template'),adminHtml:source('portable/admin.html.template'),adminScript:source('portable/admin.js.template')};
export function example(admin=false){const graph=emptyGraph(),page=makePiece('page'),form=makePiece('form',page.id),input=makePiece('input',form.id);input.props={field:'message',inputType:'text',required:true};graph.pieces.push(page,form,input);graph.entries=[page.id];return {format:'vorlda-project',version:1,name:'Isolated acceptance app',graph,assets:[],runtime:{admin}};}
export function writePortable(project){const dir=mkdtempSync(join(tmpdir(),'vorlda-admin-'));for(const file of portableFiles(project,sources)){mkdirSync(dirname(join(dir,file.name)),{recursive:true});writeFileSync(join(dir,file.name),file.content);}return dir;}
export function operator(dir,action='init',env={}){const stdout=execFileSync(process.execPath,['admin-operator.mjs',action,...(action==='reset'?['--confirm-reset']:[])],{cwd:dir,env:{PATH:process.env.PATH,...env},encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:20000});return JSON.parse(stdout.slice(stdout.indexOf('{')));}
export async function runServer(dir,env={}){const child=spawn(process.execPath,['server.mjs'],{cwd:dir,env:{PATH:process.env.PATH,PORT:'0',...env},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stderr.on('data',b=>stderr+=b);const origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{child.kill();reject(Error('Server start timed out: '+stderr));},15000);child.once('exit',()=>{clearTimeout(timer);reject(Error('Server failed: '+stderr));});child.stdout.on('data',b=>{stdout+=b;const m=stdout.match(/listening at (https?:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1]);}});});return{child,origin,stop:async()=>{const done=once(child,'exit');child.kill('SIGTERM');await done;}};}
export function adminClient(service){let cookie='',csrf='';return {get cookie(){return cookie},set cookie(v){cookie=v},get csrf(){return csrf},async request(path,body,options={}){const response=await fetch(service.origin+'/admin/api/'+path,{method:body===undefined?'GET':'POST',headers:{...(cookie?{cookie}:{}),...(body===undefined?{}:{'content-type':'application/json',origin:service.origin,'x-csrf-token':csrf}),...options.headers},body:body===undefined?undefined:JSON.stringify(body)});const setCookie=response.headers.get('set-cookie');if(setCookie)cookie=setCookie.split(';')[0];const data=await response.json();if(data.csrf)csrf=data.csrf;return{status:response.status,body:data,headers:response.headers};}};}
