import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,client} from './support.mjs';
import {grantFunds} from '../server/wallet.ts';
import {reserveStorage,storageUsage} from '../server/entitlements.ts';

async function setup(){const f=fixture();f.env.BILLING_MODE='live';f.env.REPLICATE_API_TOKEN='fixture-only-provider-token';await client(f,'/api/bootstrap');await grantFunds(f.env,'owner-id','live',1_000_000,'topup','delivery-test','Test fixture');f.sqlite.prepare('INSERT INTO settings(key,value,updated_at) VALUES(?,?,?)').run('tariffs',JSON.stringify({run:120000,approved:true,revision:2}),new Date().toISOString());f.p=(await client(f,'/api/projects','POST',{kind:'blank'})).body;f.root='/api/projects/'+f.p.id+'/production';f.q=(await client(f,f.root+'/quote','POST',{prompt:'A blue sky'})).body;return f;}
test('missing output capacity blocks generation before any provider call or wallet debit',async()=>{
 const f=await setup(),original=globalThis.fetch;let starts=0;try{globalThis.fetch=async()=>{starts++;throw Error('must not call')};await reserveStorage(f.env,'owner-id',f.p.id,1_000_000_000-await storageUsage(f.env,'owner-id')-1000);const r=await client(f,f.root+'/execute','POST',{quoteId:f.q.id});assert.equal(r.status,409);assert.equal(starts,0);assert.equal((await client(f,'/api/wallet')).body.total,1_000_000);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM production_tasks').get().n,0);}finally{globalThis.fetch=original;f.close();}
});
test('completed provider work retains its debit on delivery failure and recovers without a second paid generation',async()=>{
 const f=await setup(),original=globalThis.fetch;let starts=0,down=true;try{globalThis.fetch=async(url,options)=>{if(String(url).startsWith('https://replicate.delivery/')){if(down)throw Error('delivery network interrupted');return new Response(Uint8Array.of(137,80,78,71),{headers:{'content-type':'image/png'}});}if(options.method==='POST')starts++;return Response.json({id:'receipt',status:'succeeded',output:'https://replicate.delivery/test.png'});};const r=await client(f,f.root+'/execute','POST',{quoteId:f.q.id});assert.equal(r.status,200);assert.equal(r.body.status,'delivery_failed');assert.equal((await client(f,'/api/wallet')).body.total,880000);assert.equal((await client(f,'/api/wallet')).body.storageBreakdown.pending,25*1024*1024);assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM ledger WHERE kind='refund'").get().n,0);down=false;const retry=await client(f,f.root+'/'+r.body.id);assert.equal(retry.body.status,'completed');assert.equal(starts,1);const w=(await client(f,'/api/wallet')).body;assert.equal(w.total,880000);assert.equal(w.storageBreakdown.pending,0);assert.equal(w.storageBreakdown.assets,4);assert.equal((await client(f,JSON.parse(retry.body.output).url)).status,200);await client(f,f.root+'/execute','POST',{quoteId:f.q.id});assert.equal(starts,1);}finally{globalThis.fetch=original;f.close();}
});
test('confirmed generation failure refunds exactly once and releases its output reservation',async()=>{
 const f=await setup(),original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({id:'failed-receipt',status:'failed'});const r=await client(f,f.root+'/execute','POST',{quoteId:f.q.id});assert.equal(r.body.status,'failed');const w=(await client(f,'/api/wallet')).body;assert.equal(w.total,1_000_000);assert.equal(w.storageBreakdown.pending,0);await client(f,f.root+'/execute','POST',{quoteId:f.q.id});assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM ledger WHERE kind='refund'").get().n,1);}finally{globalThis.fetch=original;f.close();}
});
