import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
export function fixture(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
 class Statement{constructor(sql,values=[]){this.sql=sql;this.values=values}bind(...v){return new Statement(this.sql,v)}async first(column){const r=sqlite.prepare(this.sql).get(...this.values);return r?(column?r[column]:r):null}async all(){return{results:sqlite.prepare(this.sql).all(...this.values),meta:{changes:0},success:true}}async run(){return this.execute()}execute(){const s=sqlite.prepare(this.sql);if(/^(SELECT|PRAGMA)/i.test(this.sql.trim()))return{results:s.all(...this.values),meta:{changes:0},success:true};const r=s.run(...this.values);return{results:[],meta:{changes:Number(r.changes)},success:true}}}
 const DB={prepare:s=>new Statement(s),async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const result=statements.map(s=>s.execute());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};const files=new Map();const BUCKET={async put(key,value,options){const bytes=await new Response(value).arrayBuffer();files.set(key,{bytes,options})},async get(key,options){const f=files.get(key);if(!f)return null;const range=options?.range,bytes=range?f.bytes.slice(range.offset,range.offset+range.length):f.bytes;return{body:new Response(bytes).body,size:bytes.byteLength,httpMetadata:f.options?.httpMetadata}},async delete(key){files.delete(key)}};
 const env={DB,BUCKET,ASSETS:{fetch:async()=>new Response('Not found',{status:404})},APP_OWNER_EMAIL:'owner@example.test',BILLING_MODE:'test',APP_ORIGIN:'https://app.test'};
 return{env,sqlite,files,close:()=>sqlite.close()};
}
export const ownerHeaders={'oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':'owner@example.test','oai-authenticated-user-full-name':'Workshop%20Owner','oai-authenticated-user-full-name-encoding':'percent-encoded-utf-8'};
export const otherHeaders={'oai-authenticated-user-id':'other-id','oai-authenticated-user-email':'other@example.test'};
export async function client(f,path,method='GET',data,headers=ownerHeaders){const {handleApi}=await import('../server/api.ts');const request=new Request('https://app.test'+path,{method,headers:{...headers,...(data instanceof FormData?{}:{'content-type':'application/json'})},body:data===undefined?undefined:data instanceof FormData?data:JSON.stringify(data)});const response=await handleApi(request,f.env,{waitUntil(){},passThroughOnException(){}});const body=(response.headers.get('content-type')||'').includes('application/json')?await response.json():await response.text();return{status:response.status,headers:response.headers,body};}
