"use client";
import { useEffect, useState } from 'react';
import { firstInspectorTab, type InspectorTab } from '@/lib/workshop-flow';
import { type Graph, type Piece, type Fields, type Connection, descendants, absolutePosition, effectivePiece, makeConnection, id } from '@/lib/world';
import { Field, TextField, Choice, Toggle, JsonField, IconButton } from './editor-controls';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Lock, Unlock, Eye, EyeOff, Plus, Link2, X, ArrowUpRight } from 'lucide-react';
import { toast } from 'sonner';
type Props = {
    graph: Graph;
    piece: Piece;
    edit: (fn: (g: Graph) => void) => void;
    mobile: boolean;
    assets: any[];
    select: (id: string) => void;
    ar: boolean;
    advanced?: boolean;
    openCode?: () => void;
    requestedTab?: InspectorTab;
};
export function Inspector({ graph: g, piece: raw, edit, mobile, assets, select, ar, advanced = false, openCode, requestedTab }: Props) {
    const [tab, setTab] = useState<InspectorTab>(requestedTab || firstInspectorTab(raw));
    useEffect(() => { setTab(requestedTab || firstInspectorTab(raw)); }, [raw.id, requestedTab]);
    const p = effectivePiece(g, raw, mobile ? 'mobile' : 'desktop'), t = (en: string, arText: string) => ar ? arText : en;
    const patch = (v: Partial<Piece>) => edit(g => { const a = g.pieces.find(x => x.id === p.id)!; if (a.locked && v.locked !== false) {
        toast.error(t('Unlock this part first.', 'افتح قفل القطعة أولًا.'));
        return;
    } if (mobile) {
        const responsive: Fields = {};
        for (const [k, x] of Object.entries(v))
            if (['x', 'y', 'w', 'h', 'hidden'].includes(k))
                responsive[k] = x as any;
            else
                Object.assign(a, { [k]: x });
        a.mobile = { ...a.mobile, ...responsive };
    }
    else
        Object.assign(a, v); });
    const prop = (key: string, v: any) => patch({ props: { ...raw.props, [key]: v } });
    const style = (key: string, v: any) => { if (mobile)
        patch({ mobile: { ...raw.mobile, style: { ...((raw.mobile.style || {}) as Fields), [key]: v } } });
    else
        patch({ style: { ...raw.style, [key]: v } }); };
    const childIds = new Set(descendants(g, p.id).map(p => p.id));
    const edges = g.connections.filter(c => c.from === p.id);
    const color = (key: string, label: string) => <label className="field"><span>{label}</span><div className="color-field"><input type="color" aria-label={label} value={/^#[\da-f]{6}$/i.test(String(p.style[key])) ? String(p.style[key]) : '#ffffff'} onChange={e => style(key, e.target.value)}/><input aria-label={label + ' value'} value={String(p.style[key] || 'transparent')} onChange={e => style(key, e.target.value)}/></div></label>;
    return <div className="inspector-inner"><div className="inspector-heading"><span className="eyebrow">{p.type} {mobile ? '· MOBILE' : ''}</span><div className="row"><IconButton label={raw.locked ? 'Unlock' : 'Lock'} onClick={() => patch({ locked: !raw.locked })}>{raw.locked ? <Lock /> : <Unlock />}</IconButton><IconButton label={p.hidden ? 'Show' : 'Hide'} onClick={() => patch({ hidden: !p.hidden })}>{p.hidden ? <EyeOff /> : <Eye />}</IconButton></div></div><Field label={t('Part name', 'اسم القطعة')} value={p.name} onChange={name => patch({ name })}/>{raw.sourceId && <button className="source-link" onClick={() => select(raw.sourceId!)}><Link2 size={13}/>{t(raw.variant ? 'Variant of source' : 'Linked to source', 'مرتبط بالمصدر')}<ArrowUpRight size={13}/></button>}
 <Tabs value={tab} onValueChange={v => setTab(v as InspectorTab)}><TabsList className="inspector-tabs"><TabsTrigger value="design">{t('Design', 'تصميم')}</TabsTrigger><TabsTrigger value="content">{t('Content', 'محتوى')}</TabsTrigger><TabsTrigger value="actions">{t('Interaction', 'تفاعل')}</TabsTrigger></TabsList>
 <TabsContent forceMount value="design"><div className="property-section"><h3>{t('Size', 'المقاس')}</h3><div className="grid-2">{(['w', 'h'] as const).map(k => <Field key={k} label={{ x: 'X', y: 'Y', w: t('Width', 'العرض'), h: t('Height', 'الارتفاع'), rotation: t('Rotation', 'الدوران') }[k]} value={p[k]} type="number" step={1} min={['w', 'h'].includes(k) ? 1 : -1000000} max={1000000} onChange={v => patch({ [k]: v })}/>)}</div><details className="advanced-details" open={advanced}><summary>{t('Position, rotation & layout', 'الموقع والدوران والتخطيط')}</summary><div className="grid-2">{(['x', 'y', 'rotation'] as const).map(k => <Field key={k} label={{ x: 'X', y: 'Y', rotation: t('Rotation', 'الدوران') }[k]} value={p[k]} type="number" step={1} min={-1000000} max={1000000} onChange={v => patch({ [k]: v })}/>)}</div><label className="field"><span>{t('Parent', 'القطعة الحاضنة')}</span><Choice value={p.parentId || ''} label={t('Parent part', 'القطعة الحاضنة')} options={[{ value: '', label: t('Workshop', 'الورشة') }, ...g.pieces.filter(a => !childIds.has(a.id)).map(a => ({ value: a.id, label: a.name }))]} onChange={v => { const abs = absolutePosition(g, raw), parent = g.pieces.find(a => a.id === v), pos = parent ? absolutePosition(g, parent) : { x: 0, y: 0 }; patch({ parentId: v || null, x: abs.x - pos.x, y: abs.y - pos.y }); }}/></label><Choice label={t('Layout', 'التخطيط')} value={String(p.style.layout || 'absolute')} options={[{ value: 'absolute', label: t('Free positioning', 'تموضع حر') }, { value: 'row', label: t('Horizontal flow', 'صف أفقي') }, { value: 'column', label: t('Vertical flow', 'عمود رأسي') }]} onChange={v => style('layout', v)}/>{p.style.layout !== 'absolute' && <div className="grid-2"><Field label={t('Gap', 'التباعد')} value={p.style.gap} type="number" min={0} onChange={v => style('gap', v)}/><Field label={t('Padding', 'المساحة الداخلية')} value={p.style.padding} type="number" min={0} onChange={v => style('padding', v)}/></div>}</details></div>
 <div className="property-section"><h3>{t('Appearance', 'المظهر')}</h3>{color('background', t('Fill', 'لون التعبئة'))}{color('color', t('Text color', 'لون النص'))}<div className="grid-2"><Field label={t('Corner radius', 'استدارة الحواف')} value={p.style.radius} type="number" min={0} onChange={v => style('radius', v)}/><Field label={t('Font size', 'حجم الخط')} value={p.style.fontSize} type="number" min={1} onChange={v => style('fontSize', v)}/></div><Choice label={t('Weight', 'سماكة الخط')} value={String(p.style.fontWeight || '400')} options={[{ value: '400', label: 'Regular' }, { value: '500', label: 'Medium' }, { value: '600', label: 'Semibold' }, { value: '700', label: 'Bold' }]} onChange={v => style('fontWeight', v)}/><Choice label={t('Text alignment', 'محاذاة النص')} value={String(p.style.textAlign || 'left')} options={['left', 'center', 'right']} onChange={v => style('textAlign', v)}/><label className="field"><span>{t('Opacity', 'الشفافية')} <b>{Math.round(Number(p.style.opacity ?? 1) * 100)}%</b></span><Slider aria-label="Opacity" value={[Number(p.style.opacity ?? 1) * 100]} min={0} max={100} step={1} onValueChange={v => style('opacity', v[0] / 100)}/></label></div>
 {mobile && <div className="property-section"><p className="muted">{t('Changes here override the desktop layout only on small screens.', 'تطبق تعديلات هذا الوضع على الشاشات الصغيرة فقط.')}</p><Button variant="outline" onClick={() => patch({ mobile: {} })}>{t('Reset mobile overrides', 'إلغاء تخصيص الجوال')}</Button></div>}
 <details className="property-section advanced-details" open={advanced}><summary>{t('Advanced layout details', 'تفاصيل التصميم المتقدمة')}</summary><JsonField label={t('Responsive overrides (JSON)', 'تخصيص الجوال (JSON)')} value={raw.mobile} onChange={v => { if (!v || Array.isArray(v) || typeof v !== 'object')
        throw Error('Use an object.'); patch({ mobile: v }); }}/></details></TabsContent>
 <TabsContent forceMount value="content"><div className="property-section">
 {['text', 'button', 'prompt'].includes(p.type) && <TextField label={t(p.type === 'prompt' ? 'Instructions' : 'Text', p.type === 'prompt' ? 'التعليمات' : 'النص')} value={p.props.text} onChange={v => prop('text', v)} rows={5}/>}
 {['image', 'video', 'audio'].includes(p.type) && <><Choice label={t('Imported asset', 'الملف المستورد')} value={String(p.props.src || '')} options={[{ value: '', label: t('Choose imported media', 'اختر ملفًا مستوردًا') }, ...assets.filter(a => a.content_type.startsWith(p.type + '/')).map(a => ({ value: '/api/assets/' + a.id, label: a.name }))]} onChange={v => prop('src', v)}/><Field label={t('Media URL', 'رابط الملف')} value={p.props.src} onChange={v => prop('src', v)}/></>}
 {p.type === 'image' && <><Field label={t('Alt text', 'وصف الصورة')} value={p.props.alt} onChange={v => prop('alt', v)}/><Choice label={t('Fit', 'احتواء الصورة')} value={String(p.props.fit || 'cover')} options={[{value:'cover',label:t('Fill the frame', 'ملء الإطار')},{value:'contain',label:t('Show full image', 'إظهار الصورة كاملة')}]} onChange={v => prop('fit', v)}/><details className="advanced-details" open={advanced}><summary>{t('Crop, mask & image adjustments', 'القص والقناع وضبط الصورة')}</summary><Choice label={t('Mask', 'قناع الصورة')} value={String(p.props.mask || 'none')} options={['none', 'circle', 'ellipse']} onChange={v => prop('mask', v)}/>{[['brightness', 0, 200], ['contrast', 0, 200], ['saturation', 0, 200], ['blur', 0, 30], ['hue', 0, 360], ['cropX', 0, 100], ['cropY', 0, 100], ['cropZoom', 1, 5]].map(([key, min, max]) => <label className="field" key={key}><span>{String(key)} <b>{String(p.props[key] ?? (key === 'cropZoom' ? 1 : String(key).startsWith('crop') ? 50 : ['brightness', 'contrast', 'saturation'].includes(String(key)) ? 100 : 0))}</b></span><Slider aria-label={String(key)} min={Number(min)} max={Number(max)} step={key === 'cropZoom' ? .05 : 1} value={[Number(p.props[key] ?? (key === 'cropZoom' ? 1 : String(key).startsWith('crop') ? 50 : ['brightness', 'contrast', 'saturation'].includes(String(key)) ? 100 : 0))]} onValueChange={v => prop(String(key), v[0])}/></label>)}</details></>}
 {['video', 'audio'].includes(p.type) && <><div className="grid-2">{['start', 'duration', 'trim', 'speed', 'volume'].map(key => <Field key={key} label={key} value={p.props[key]} type="number" min={key === 'speed' ? .25 : 0} max={key === 'volume' ? 1 : key === 'speed' ? 4 : 3600} step={.1} onChange={v => prop(key, v)}/>)}</div><Toggle label={t('Loop', 'تكرار')} checked={!!p.props.loop} onChange={v => prop('loop', v)}/><JsonField label="Keyframes: time, x, y, opacity, rotation, scale" value={p.props.keyframes || []} onChange={v => { if (!Array.isArray(v))
        throw Error('Use an array.'); prop('keyframes', v); }}/></>}
 {p.type === 'shape' && <Choice label={t('Geometry', 'الشكل')} value={String(p.props.shape || 'rectangle')} options={['rectangle', 'ellipse']} onChange={v => prop('shape', v)}/>}
 {p.type === 'input' && <><Field label={t('Field key', 'اسم الحقل الداخلي')} value={p.props.field} onChange={v => prop('field', v)}/><Field label={t('Placeholder', 'النص الإرشادي')} value={p.props.placeholder} onChange={v => prop('placeholder', v)}/><Choice label={t('Input type', 'نوع الحقل')} value={String(p.props.inputType || 'text')} options={['text', 'email', 'number', 'password', 'date', 'tel']} onChange={v => prop('inputType', v)}/><Toggle label={t('Required', 'مطلوب')} checked={!!p.props.required} onChange={v => prop('required', v)}/></>}
 {p.type === 'form' && <><Field label={t('Submit button', 'نص زر الإرسال')} value={p.props.submitLabel} onChange={v => prop('submitLabel', v)}/><TextField label={t('Success message', 'رسالة النجاح')} value={p.props.success} onChange={v => prop('success', v)}/><p className="muted">{t('Add inputs inside this form. Published responses appear in Project → Responses.', 'أضف حقولًا داخل النموذج. تظهر الردود بعد نشره في بيانات المشروع.')}</p></>}
 {p.type === 'data' && <><Field label="Collection name" value={p.props.collection} onChange={v => prop('collection', v)}/><JsonField label="Records" value={p.props.records || []} onChange={v => { if (!Array.isArray(v))
        throw Error('Use an array of records.'); prop('records', v); }}/></>}
 {p.type === 'gallery' && <><Field label="Columns" type="number" min={1} max={8} value={p.props.columns} onChange={v => prop('columns', v)}/><JsonField label="Image URLs" value={p.props.images || []} onChange={v => { if (!Array.isArray(v))
        throw Error('Use an array of URLs.'); prop('images', v); }}/></>}
 {p.type === 'code' && (p.props.workspace ? <Button variant="outline" onClick={openCode}>{t('Open source files', 'فتح ملفات المشروع')}</Button> : <><TextField label="Isolated HTML" value={p.props.html} onChange={v => prop('html', v)} rows={12}/><p className="muted">{t('Runs in a sandbox. It cannot read workshop data or call external APIs.', 'يعمل داخل إطار معزول ولا يصل إلى بيانات الورشة أو الواجهات الخارجية.')}</p></>)}
 {p.type === 'character' && <><Field label="Stable identity" value={p.props.identity} onChange={v => prop('identity', v)}/><TextField label="Description" value={p.props.description} onChange={v => prop('description', v)}/><JsonField label="Reference image URLs" value={p.props.references || []} onChange={v => prop('references', v)}/><JsonField label="Identity anchors" value={p.props.anchors || []} onChange={v => prop('anchors', v)}/><Toggle label={t('I have rights to these references', 'لدي حقوق استخدام هذه المراجع')} checked={!!p.props.consent} onChange={v => prop('consent', v)}/></>}
 {p.type === 'prompt' && <><Choice label="Target" value={String(p.props.target || '')} options={[{ value: '', label: 'Global' }, ...g.pieces.filter(a => a.id !== p.id).map(a => ({ value: a.id, label: a.name }))]} onChange={v => prop('target', v)}/><p className="muted">{t('Instructions are saved with their target. Generation needs a connected provider.', 'تُحفظ التعليمات مع هدفها. التنفيذ الذكي يتطلب ربط مزوّد.')}</p></>}
 {p.type === 'generator' && <><TextField label="Generation prompt" value={p.props.prompt} onChange={v => prop('prompt', v)}/><Choice label="Operation" value={String(p.props.operation || 'image')} options={['image', 'video', 'audio', 'assembly', 'enhance', 'decompose', 'structural-3d']} onChange={v => prop('operation', v)}/><div className="notice">{t('Provider not connected. No request will be sent and no balance will be deducted.', 'المزوّد غير مربوط. لن يرسل طلب ولن يخصم رصيد.')}</div></>}
 <details className="advanced-details" open={advanced}><summary>{t('Advanced properties', 'خصائص متقدمة')}</summary><JsonField label={t('All properties', 'كل الخصائص')} value={raw.props} onChange={v => { if (!v || Array.isArray(v) || typeof v !== 'object')
        throw Error('Use an object.'); patch({ props: v }); }}/></details></div></TabsContent>
 <TabsContent forceMount value="actions"><div className="property-section"><h3>{t('Connections', 'الروابط')}<Button size="icon" variant="ghost" aria-label="Add connection" onClick={() => edit(g => g.connections.push(makeConnection(p.id, null)))}><Plus size={15}/></Button></h3>{edges.length === 0 && <p className="muted">{t('Connect this part to a destination, data collection, or action.', 'اربط القطعة بوجهة أو مجموعة بيانات أو إجراء.')}</p>}{edges.map(c => <ConnectionEditor key={c.id} connection={c} graph={g} edit={edit} ar={ar} advanced={advanced}/>)}</div>
 {p.type === 'page' && <div className="property-section"><Toggle label={t('Available as an entry', 'متاح كنقطة دخول')} checked={g.entries.includes(p.id)} onChange={on => edit(g => { g.entries = on ? [...g.entries, p.id] : g.entries.filter(k => k !== p.id); })}/><p className="muted">{t('Entry points are optional; your application has no mandatory home page.', 'نقاط الدخول اختيارية؛ لا تفرض الورشة صفحة رئيسية.')}</p></div>}</TabsContent>
 </Tabs></div>;
}
function ConnectionEditor({ connection: c, graph, edit, ar, advanced }: {
    connection: Connection;
    ar: boolean;
    advanced: boolean;
    graph: Graph;
    edit: (fn: (g: Graph) => void) => void;
}) { const t = (en: string, a: string) => ar ? a : en; const patch = (v: Partial<Connection>) => edit(g => Object.assign(g.connections.find(e => e.id === c.id)!, v)); return <div className="connection-editor"><div className="row between"><Link2 size={14}/><span>{c.to ? t('Connected', 'متصل') : t('Choose destination', 'اختر الوجهة')}</span><IconButton label="Remove connection" onClick={() => edit(g => { g.connections = g.connections.filter(e => e.id !== c.id); })}><X size={14}/></IconButton></div><Field label={t("Label", "اسم الرابط")} value={c.label} onChange={v => patch({ label: v })}/><Choice label={t("Destination", "الوجهة")} value={c.to || ''} options={[{ value: '', label: t('Unconnected', 'دون وجهة') }, ...graph.pieces.map(p => ({ value: p.id, label: p.name }))]} onChange={v => patch({ to: v || null })}/><Choice label={t("Action type", "نوع التفاعل")} value={c.type} options={[{value:'navigation',label:t('Navigate', 'انتقال')},{value:'data',label:t('Data', 'بيانات')},{value:'transform',label:t('Transform', 'تحويل')},{value:'storage',label:t('Storage', 'تخزين')},{value:'return',label:t('Go back', 'رجوع')},{value:'generation',label:t('Generate', 'توليد')}]} onChange={v => patch({ type: v as Connection['type'] })}/><Toggle label={t("Disable this connection", "تعطيل هذا الرابط")} checked={c.disabled} onChange={v => patch({ disabled: v })}/><details className="advanced-details" open={advanced}><summary>{t("Event, conditions & navigation", "الحدث والشروط وسلوك التنقل")}</summary><div className="grid-2"><Choice label={t("Event", "الحدث")} value={c.event} options={['click', 'submit']} onChange={v => patch({ event: v })}/><Choice label={t('Open behavior', 'طريقة الفتح')} value={c.open} options={['replace', 'overlay', 'panel', 'split', 'background']} onChange={v => patch({ open: v as Connection['open'] })}/></div><Choice label={t('History', 'سجل التنقل')} value={c.history} options={['push', 'replace', 'clear']} onChange={v => patch({ history: v as Connection['history'] })}/><Choice label={t('Back behavior', 'سلوك الرجوع')} value={c.back} options={['history', 'source', 'none']} onChange={v => patch({ back: v as Connection['back'] })}/><Field label={t('Condition: field=value', 'شرط: الحقل=القيمة')} value={c.condition} onChange={v => patch({ condition: v })}/><Toggle label={t('Preserve state', 'الاحتفاظ بالحالة')} checked={c.preserve} onChange={v => patch({ preserve: v })}/>{c.type === 'transform' && <JsonField label="Steps: filter, sort, limit, set" value={c.steps} onChange={v => { if (!Array.isArray(v))
    throw Error('Use an array.'); patch({ steps: v }); }}/>}</details></div>; }
