"use client";
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Field,TextField,Choice } from './editor-controls';
import { api,type Project } from '@/lib/client';
import { money } from '@/lib/money';
import { downloadBlob } from '@/lib/media';
import { zipFiles } from '@/lib/zip';
import { toast } from 'sonner';
import { Play,RefreshCw,Download,ImageIcon,Check } from 'lucide-react';
export function ProductionPanel({project,projects,wallet,refresh,ar}:{project:Project;projects:any[];wallet:any;refresh:()=>Promise<void>;ar:boolean}){
 const t=(en:string,a:string)=>ar?a:en,[state,setState]=useState<any>(null),[prompt,setPrompt]=useState(''),[aspect,setAspect]=useState('1:1'),[quote,setQuote]=useState<any>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([project.id]);
 async function reload(){setState(await api(`/api/projects/${project.id}/production`));}
 useEffect(()=>{void reload().catch(e=>toast.error(e.message));},[project.id]);
 useEffect(()=>{if(!state?.tasks.some((r:any)=>['running','delivering'].includes(r.status)))return;let running=false;const timer=setInterval(async()=>{if(running)return;running=true;try{for(const r of state.tasks.filter((r:any)=>['running','delivering'].includes(r.status)))await api(`/api/projects/${project.id}/production/${r.id}`);await reload();await refresh();}catch{}finally{running=false}},5000);return()=>clearInterval(timer)},[state?.tasks,project.id]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function review(kind:string){await action(async()=>{setQuote(await api(`/api/projects/${project.id}/production/quote`,{method:'POST',body:{kind,prompt,aspect}}))})}
 const labels:Record<string,string>={reserved:t('Reserved','محجوزة'),starting:t('Starting','تبدأ'),running:t('Generating','جار التوليد'),delivering:t('Saving image','جار حفظ الصورة'),delivery_failed:t('Delivery needs retry','إعادة محاولة التسليم'),completed:t('Completed','مكتملة'),failed:t('Refunded','أعيد الرصيد'),uncertain:t('Owner review needed','تحتاج مراجعة المالك')};
 return <div dir={ar?'rtl':'ltr'}><Tabs defaultValue="generate"><TabsList className="project-tabs"><TabsTrigger value="generate">{t('Generate','الإنتاج')}</TabsTrigger><TabsTrigger value="batch">{t('Batch export','تصدير دفعة')}</TabsTrigger><TabsTrigger value="history">{t('Activity','العمليات')}</TabsTrigger></TabsList>
 <TabsContent value="generate"><div className="wallet-help"><strong>{t('Image generation','توليد الصور')}</strong><p>{state?.providerReady?t('Describe the image, review its price, then start. Finished images are saved to this project.','صف الصورة، وراجع السعر، ثم ابدأ. تُحفظ الصور الناتجة في ملفات هذا المشروع.'):t('Image generation needs the provider connection. You can compose with your own images and test the wallet below.','توليد الصور يحتاج ربط المزوّد. تستطيع التصميم بصورك وتجربة المحفظة أدناه.')}</p></div><TextField label={t('Image description','وصف الصورة')} value={prompt} onChange={v=>{setPrompt(v);setQuote(null)}}/><Choice label={t('Aspect ratio','نسبة الأبعاد')} value={aspect} onChange={v=>{setAspect(v);setQuote(null)}} options={['1:1','16:9','9:16','4:3','3:4'].map(v=>({value:v,label:v}))}/><div className="row"><Button disabled={busy||!state?.providerReady||!prompt.trim()} onClick={()=>review('image')}><ImageIcon size={16}/>{t('Review price','مراجعة السعر')}</Button>{wallet.mode==='test'&&<Button variant="outline" disabled={busy} onClick={()=>review('billing-test')}>{t('Test a paid operation','اختبر عملية مدفوعة')}</Button>}</div>
 {quote&&<div className="resource-card" style={{marginTop:16}}><strong>{quote.kind==='billing-test'?t('Billing test — no image will be generated','اختبار للخصم — لن تُولّد صورة'):t('Your image quote','عرض تكلفة الصورة')}</strong><p>{t('Deducted before execution','يُخصم قبل التنفيذ')}: <b dir="ltr">{money(quote.amount)}</b></p><p className="muted">{quote.billedTo==='project_owner'?t('Paid from the project owner’s wallet, within your allowance.','يُخصم من محفظة مالك المشروع ضمن حد الصرف الممنوح لك.'):t('Paid from subscription or top-up credit; welcome credit is not eligible. Failed generation is refunded. Completed generation stays charged if delivery needs a retry.','يُخصم من رصيد الاشتراك أو الشحن؛ الترحيبي غير مؤهل. فشل التوليد يعيد الرصيد. إذا اكتمل التوليد وتعثر التسليم يبقى الخصم وتُعاد محاولة التسليم.')}</p><p>{t('Eligible balance before execution','الرصيد المؤهل قبل التنفيذ')}: <b dir="ltr">{money(quote.eligibleBalance||0)}</b></p><p>{t('Balance after this operation','الرصيد بعد العملية')}: <b dir="ltr">{money(Math.max(0,(quote.eligibleBalance||0)-quote.amount))}</b></p>{quote.eligibleBalance<quote.amount&&<p role="status">{t('Insufficient eligible credit. Top up before executing.','الرصيد المؤهل غير كافٍ. اشحن قبل التنفيذ.')}</p>}<Button disabled={busy||quote.eligibleBalance<quote.amount} onClick={()=>action(async()=>{await api(`/api/projects/${project.id}/production/execute`,{method:'POST',body:{quoteId:quote.id}});setQuote(null);await reload();await refresh();toast.success(t('Operation recorded.','سُجلت العملية.'))})}><Check size={16}/>{t('Approve and execute','موافقة وتنفيذ')}</Button></div>}</TabsContent>
 <TabsContent value="batch"><p className="muted">{t('Download applied applications together as a ZIP. Projects with private media must be exported individually to embed their originals.','نزّل التطبيقات المعتمدة معًا في ZIP. المشاريع ذات الوسائط الخاصة تُصدّر منفردة لدمج ملفاتها الأصلية.')}</p><p>{t('Batch limit','حد الدفعة')}: {state?.entitlement?.batch||1}</p>{projects.filter(p=>p.owner===project.owner).map(p=><label className="list-item" key={p.id}><span className="row"><Checkbox checked={selected.includes(p.id)} onCheckedChange={v=>setSelected(v?[...selected,p.id]:selected.filter(k=>k!==p.id))}/>{p.name}</span><small>v{p.revision}</small></label>)}<Button disabled={busy||!selected.length} onClick={()=>action(async()=>{const r=await api(`/api/projects/${project.id}/production/batch-export`,{method:'POST',body:{projectIds:selected}});downloadBlob(zipFiles(r.files),'vorlda-applications.zip')})}><Download size={16}/>{t('Export selected projects','تصدير المشاريع المحددة')}</Button></TabsContent>
 <TabsContent value="history"><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{for(const r of state?.tasks||[])if(['running','delivering','delivery_failed'].includes(r.status))await api(`/api/projects/${project.id}/production/${r.id}`);await reload();await refresh()})}><RefreshCw size={16}/>{t('Refresh','تحديث')}</Button>{state?.tasks?.length?state.tasks.map((r:any)=><article className="resource-card" key={r.id} style={{marginTop:12}}><div className="row between"><strong>{r.kind==='billing-test'?t('Billing test','اختبار الخصم'):t('Generated image','توليد صورة')}</strong><span className={'task-state '+r.status}>{labels[r.status]||r.status}</span></div><p dir="ltr">{money(r.amount)} · {new Date(r.created_at).toLocaleString(ar?'ar':'en')}</p>{r.error&&<p role="status">{r.error}</p>}{r.output&&JSON.parse(r.output).url&&<a href={JSON.parse(r.output).url+'?download=1'}>{t('Download original image','تنزيل الصورة الأصلية')}</a>}</article>):<p className="empty-row">{t('Your production history will appear here.','ستظهر عمليات الإنتاج هنا.')}</p>}</TabsContent></Tabs></div>;
}
