"use client";
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Field,TextField } from './editor-controls';
import { api } from '@/lib/client';
import { type Graph } from '@/lib/world';
import { toast } from 'sonner';
import { Plus,Trash2,Palette,Copy } from 'lucide-react';
export function ResourceLibrary({graph,ar,onPreset,onBrand}:{graph:Graph;ar:boolean;onPreset:(name:string,g:Graph)=>Promise<void>;onBrand:(kit:any)=>void}){
 const t=(en:string,a:string)=>ar?a:en,[data,setData]=useState<any>({items:[]}),[name,setName]=useState(''),[colors,setColors]=useState('#1454ff, #ffffff, #111827'),[font,setFont]=useState('Arial'),[instructions,setInstructions]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState<any>(null);
 async function load(){setData(await api('/api/resources'))}useEffect(()=>{void load().catch(e=>toast.error(e.message))},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn();await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <div dir={ar?'rtl':'ltr'}><Tabs defaultValue="presets"><TabsList className="project-tabs"><TabsTrigger value="presets">{t('Production presets','إعدادات الإنتاج')}</TabsTrigger><TabsTrigger value="brands">{t('Brand kits','هويات المشاريع')}</TabsTrigger></TabsList>
 <TabsContent value="presets"><p className="muted">{t('Save this composition as a starting point. Using a preset creates a new project and preserves your current work. Project-specific media stays in its source project.','احفظ التركيبة كنقطة انطلاق. استخدام الإعداد ينشئ مشروعًا جديدًا ويحافظ على عملك الحالي. ملفات الوسائط الخاصة تبقى في مشروعها الأصلي.')}</p><div className="row"><Field label={t('Preset name','اسم الإعداد')} value={name} onChange={setName}/><Button disabled={busy||!name.trim()||!data.entitlement?.presets} onClick={()=>action(async()=>{await api('/api/resources',{method:'POST',body:{kind:'preset',name,data:graph}});setName('');toast.success(t('Preset saved.','حُفظ إعداد الإنتاج.'))})}><Plus size={16}/>{t('Save current composition','حفظ التركيبة الحالية')}</Button></div>{!data.entitlement?.presets&&<p className="notice">{t('Saving new presets requires Starter or above.','حفظ إعدادات جديدة متاح في Starter وما فوق.')}</p>}<div className="resource-grid">{data.items.filter((r:any)=>r.kind==='preset').map((r:any)=><article className="resource-card" key={r.id}><Copy size={22}/><strong>{r.name}</strong><p className="muted">{t('Saved revision','النسخة المحفوظة')} {r.revision}</p><div className="row"><Button disabled={busy} onClick={()=>action(async()=>{const full=await api('/api/resources/'+r.id);await onPreset(full.name,full.data)})}>{t('Create project','إنشاء مشروع')}</Button><Button variant="ghost" aria-label={t('Delete preset','حذف الإعداد')} onClick={()=>setRemove(r)}><Trash2 size={16}/></Button></div></article>)}</div></TabsContent>
 <TabsContent value="brands"><p className="muted">{t('Keep reusable colors, typography and creative instructions for each identity. Apply a kit to the current draft, then review the result.','احتفظ بألوان وخط وتعليمات لكل هوية. طبّق الهوية على المسودة الحالية ثم راجع النتيجة.')}</p><div className="grid-2"><Field label={t('Brand name','اسم الهوية')} value={name} onChange={setName}/><Field label={t('Colors, separated by commas','الألوان مفصولة بفواصل')} value={colors} onChange={setColors}/><Field label={t('Font family','عائلة الخط')} value={font} onChange={setFont}/></div><TextField label={t('Creative instructions','تعليمات الهوية')} value={instructions} onChange={setInstructions}/><Button disabled={busy||!name.trim()||!data.entitlement?.brands} onClick={()=>action(async()=>{await api('/api/resources',{method:'POST',body:{kind:'brand',name,data:{colors:colors.split(',').map(s=>s.trim()),font,instructions}}});setName('');toast.success(t('Brand saved.','حُفظت الهوية.'))})}><Plus size={16}/>{t('Save brand kit','حفظ الهوية')}</Button>{!data.entitlement?.brands&&<p className="notice">{t('Brand management requires Pro or Studio.','إدارة الهويات متاحة في Pro وStudio.')}</p>}<div className="resource-grid">{data.items.filter((r:any)=>r.kind==='brand').map((r:any)=><article className="resource-card" key={r.id}><Palette size={22}/><strong>{r.name}</strong><div className="row">{r.data.colors.map((c:string,i:number)=><span key={i} className="resource-swatch" style={{background:c}} title={c}/>)}</div><p className="muted">{r.data.font} · {r.data.instructions}</p><div className="row"><Button disabled={busy} onClick={()=>onBrand(r)}>{t('Apply to draft','تطبيق على المسودة')}</Button><Button variant="ghost" aria-label={t('Delete brand','حذف الهوية')} onClick={()=>setRemove(r)}><Trash2 size={16}/></Button></div></article>)}</div></TabsContent></Tabs>
 <AlertDialog open={!!remove} onOpenChange={v=>!v&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Delete this saved resource?','حذف هذا المورد المحفوظ؟')}</AlertDialogTitle><AlertDialogDescription>{t('Projects already created from it will be kept.','ستبقى المشاريع التي أنشأتها باستخدامه محفوظة.')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t('Cancel','إلغاء')}</AlertDialogCancel><AlertDialogAction onClick={()=>action(async()=>{await api('/api/resources/'+remove.id,{method:'DELETE'});setRemove(null)})}>{t('Delete','حذف')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
