"use client";
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Field,Toggle} from './editor-controls';
import {api} from '@/lib/client';
import {money,USD_SCALE} from '@/lib/money';
import {id} from '@/lib/world';
import {toast} from 'sonner';
import {ArrowUpRight,Check,Gift,LayoutTemplate} from 'lucide-react';

export function TemplateStore({wallet,refresh,onOpen,ar}:{wallet:any;refresh:()=>Promise<void>;onOpen:(id:string)=>Promise<void>;ar:boolean}){
 const t=(en:string,a:string)=>ar?a:en,[catalog,setCatalog]=useState<any>(null),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),request=useRef(id());
 useEffect(()=>{api('/api/templates').then(setCatalog).catch(e=>toast.error(e.message))},[]);
 const available=(wallet.total||0)+(wallet.promotion?.balance||0);
 async function claim(){setBusy(true);try{await api('/api/wallet/welcome',{method:'POST',body:{}});await refresh();}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function buy(){if(!selected)return;setBusy(true);try{
   const r=await api('/api/templates/purchase',{method:'POST',body:{templateId:selected.id,version:selected.version,expectedAmount:selected.amount,requestId:request.current,language:ar?'ar':'en'}});
   await refresh();await onOpen(r.project_id);
 }catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className="template-store" dir={ar?'rtl':'ltr'} aria-label={t('Ready-made templates','القوالب الجاهزة')}>
  <div className="row between"><h3 className="row"><LayoutTemplate size={18}/>{t('A ready-made start','بداية جاهزة')}</h3><span className="mode-tag">{catalog?.mode==='test'?t('TEST PRICES','أسعار تجريبية'):t('ONE-TIME PURCHASE','شراء مرة واحدة')}</span></div>
  <p className="muted">{t('Buy a prepared, editable project once. Future manual edits, reuse and export have no extra template fee and stay within your storage allowance.','اشترِ مشروعًا مجهزًا وقابلًا للتعديل مرة واحدة. التعديل اليدوي وإعادة الاستخدام والتصدير دون رسم إضافي للقالب وضمن مساحة حسابك.')}</p>
  {wallet.promotion?.available&&<div className="template-welcome"><Gift size={22}/><div><strong>{t('Start with $10 welcome credit','ابدأ برصيد ترحيبي 10 دولارات')}</strong><p>{t('For these templates only. Once per eligible account/email; subject to the offer budget.','لهذه القوالب فقط. مرة للحساب أو البريد المؤهل وضمن ميزانية العرض.')}</p></div><Button variant="outline" disabled={busy} onClick={claim}>{t('Claim credit','استلم الرصيد')}</Button></div>}
  <div className="template-options">{catalog?.items.map((item:any)=><button type="button" disabled={busy} key={item.id} aria-pressed={selected?.id===item.id} className={'template-option '+(selected?.id===item.id?'selected':'')} onClick={()=>{setSelected(item);request.current=id()}}><span className="template-art" style={{'--template-accent':item.accent} as React.CSSProperties}><span/><span/><span/></span><strong>{ar?item.ar:item.name}</strong><small>{item.pages} {t('pages','صفحات')} · {item.projectId?t('Purchased','تم شراؤه'):money(item.amount)}</small></button>)}</div>
  {!catalog&&<p role="status">{t('Loading templates…','جار تحميل القوالب…')}</p>}
  {selected&&<div className="template-review"><div className="row between"><strong>{ar?selected.ar:selected.name}</strong><span>{selected.projectId?t('Yours to keep','ملكك للاستخدام'):money(selected.amount)}</span></div><p>{ar?selected.descriptionAr:selected.description}</p><iframe key={selected.id+ar} title={t('Interactive template preview','معاينة تفاعلية للقالب')} src={`/api/templates/${selected.id}/preview?language=${ar?'ar':'en'}`} sandbox="allow-scripts" className="template-preview"/><p className="muted">{t('Preview forms do not submit. Your purchased project saves enquiries after publishing inside your workspace.','نماذج المعاينة لا ترسل بيانات. المشروع المشترى يحفظ الاستفسارات بعد نشره داخل مساحة عملك.')}</p>
   {selected.projectId?<Button disabled={busy} onClick={()=>onOpen(selected.projectId)}>{t('Open purchased project','افتح مشروعك المشترى')}<ArrowUpRight size={16}/></Button>:<><div className="quote-line"><span>{t('Eligible balance','الرصيد المؤهل')}</span><strong dir="ltr">{money(available)}</strong></div><div className="quote-line"><span>{t('Balance after purchase','الرصيد بعد الشراء')}</span><strong dir="ltr">{money(Math.max(0,available-selected.amount))}</strong></div><p className="muted">{t('Welcome credit is used first, then subscription credit, then top-ups. Delivery and deduction happen together. Downloads and undo do not recharge or refund this completed purchase.','يُستخدم الترحيبي أولًا ثم رصيد الاشتراك ثم الشحن. التسليم والخصم معًا. التنزيل أو التراجع عن التعديل لا يكرران الخصم ولا يعيدان ثمن الشراء المكتمل.')}</p>{available<selected.amount&&<p role="status">{t('Add eligible credit in your wallet to continue.','أضف رصيدًا مؤهلًا في المحفظة للمتابعة.')}</p>}<Button disabled={busy||available<selected.amount||!catalog?.enabled} onClick={buy}><Check size={16}/>{busy?t('Creating your project…','جار إنشاء مشروعك…'):t('Buy and create for ','شراء وإنشاء مقابل ')+money(selected.amount)}</Button>{!catalog?.enabled&&<p className="muted">{t('Purchases are not enabled in this billing mode.','الشراء لم يُفعّل في وضع الفوترة الحالي.')}</p>}</>}
  </div>}
 </section>;
}

export function CommerceSettings({ar}:{ar:boolean}){
 const t=(en:string,a:string)=>ar?a:en,[state,setState]=useState<any>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/api/admin/commerce').then(setState).catch(e=>toast.error(e.message))},[]);
 if(!state)return null;const p=state.policy,patch=(value:any)=>setState({...state,policy:{...p,...value}});
 return <section className="template-policy"><h3>{t('Templates & welcome budget','القوالب وميزانية الترحيب')}</h3><p className="muted">{state.mode==='test'?t('Test settings affect test balances only. Live purchases and live welcome grants start disabled.','هذه الإعدادات تخص الرصيد التجريبي فقط. الشراء والمنح الحقيقية معطّلان افتراضيًا.'):t('These controls affect live service credit. Review the offer budget before enabling.','هذه الضوابط تخص رصيد الخدمات الحقيقي. راجع ميزانية العرض قبل التفعيل.')}</p><Toggle label={t('Enable $2–$3 template purchases','تفعيل شراء القوالب بسعر 2–3 دولارات')} checked={p.templatesEnabled} onChange={v=>patch({templatesEnabled:v})}/><Toggle label={t('Enable the one-time $10 welcome offer','تفعيل عرض الترحيب 10 دولارات مرة واحدة')} checked={p.welcomeEnabled} onChange={v=>patch({welcomeEnabled:v})}/><div className="grid-2"><Field label={t('Daily grant cap ($)','سقف المنح اليومي ($)')} type="number" min={0} step={10} value={p.dailyGrantLimitMicros/USD_SCALE} onChange={v=>patch({dailyGrantLimitMicros:Math.round(v*USD_SCALE)})}/><Field label={t('Campaign lifetime cap ($)','سقف الحملة كاملًا ($)')} type="number" min={0} step={10} value={p.totalGrantLimitMicros/USD_SCALE} onChange={v=>patch({totalGrantLimitMicros:Math.round(v*USD_SCALE)})}/></div><p className="muted">{t('Turning the offer off does not erase previous claims. Credit has no cash value and cannot pay for image generation.','إيقاف العرض لا يمسح سجل المنح السابقة. الرصيد غير نقدي ولا يُستخدم لتوليد الصور.')}</p><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/admin/commerce',{method:'PUT',body:{policy:p}});toast.success(t('Offer settings saved.','حُفظت إعدادات العرض.'))}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}>{t('Save offer settings','حفظ إعدادات العرض')}</Button></section>;
}
