import {compileHTML} from './compiler.ts';
import {checkPublish} from './world.ts';
import {formFields,formIsVisible} from './forms.ts';
import {validateProjectBundle} from './project-io.ts';
export type PortableSources={world:string;compiler:string;forms:string;projectIo:string;build:string;server:string;responses:string};
export function portableFiles(value:unknown,sources:PortableSources){
 const project=validateProjectBundle(value),errors=checkPublish(project.graph).filter(i=>i.severity==='error');
 if(errors.length)throw Error(errors.map(i=>i.message).join('\n'));
 for(const form of project.graph.pieces.filter(p=>p.type==='form'&&formIsVisible(project.graph,p.id)))formFields(project.graph,form.id);
 const html=compileHTML(project.graph,{title:project.name,entry:project.entry,formEndpoint:'/api/forms',assetUrls:Object.fromEntries(project.assets.map(a=>[a.path,a.data]))});
 if(/\/api\/assets\/|blob:/.test(html))throw Error('An asset is missing from this bundle or still uses a temporary URL.');
 const files=[{name:'project.vorlda.json',content:JSON.stringify(project,null,2)},{name:'public/index.html',content:html},
  ...(['world','compiler','forms'] as const).map(k=>({name:`src/${k}.ts`,content:sources[k]})),{name:'src/project-io.ts',content:sources.projectIo},
  ...(['build','server','responses'] as const).map(k=>({name:k+'.mjs',content:sources[k]})),
  {name:'package.json',content:JSON.stringify({name:'vorlda-export',version:'1.0.0',private:true,type:'module',engines:{node:'>=24'},scripts:{build:'node build.mjs',start:'node server.mjs',responses:'node responses.mjs',test:'node --test test.mjs'}},null,2)},
  {name:'.gitignore',content:'data/\n.env\nnode_modules/\n'},
  {name:'.env.example',content:'HOST=127.0.0.1\nPORT=3000\n# Only after configuring HTTPS and persistent disk:\n# PUBLIC_APP=1\n# HOST=0.0.0.0\n# APP_ORIGIN=https://your-domain.example\n'},
  {name:'test.mjs',content:"import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport {project} from './build.mjs';\nimport {validateProjectBundle} from './src/project-io.ts';\ntest('project round trip',()=>assert.deepEqual(validateProjectBundle(project),project));\n"},
  {name:'README.md',content:`# ${project.name.replace(/[\r\n]/g,' ')} — native VORLDA application\n\nRequires Node.js 24 or newer. No npm install, platform account, API keys or network downloads are required.\n\n1. Extract all files. Open this folder in VS Code, Cursor or another editor.\n2. Run \`npm test\`, then \`npm start\`.\n3. Open http://127.0.0.1:3000. Forms persist in data/forms.sqlite.\n4. Run \`npm run responses\` locally to export submissions as JSON Lines. This output contains personal data; protect it.\n\n## Source and portability\nEdit project.vorlda.json for native visual structure; src/world.ts defines the schema, src/compiler.ts builds the frontend, src/forms.ts validates forms, server.mjs supplies the forms backend. Rebuild with npm run build. Import project.vorlda.json into VORLDA to recover the visual project and original assets. Changes made directly to compiler/server source do not round-trip into the visual editor. Arbitrary React/Flutter applications cannot be imported this way.\n\n## Deployment\nUse a Node host with a persistent, writable data directory and TLS reverse proxy. Stop the process before copying the entire data directory for a consistent backup, then test restore. Set PUBLIC_APP=1, HOST=0.0.0.0 and APP_ORIGIN to the exact HTTPS origin; use node --env-file=.env server.mjs if storing configuration in .env. Set a restrictive OS umask such as 077. Never serve the project root: only public/index.html is intended for visitors. The supplied server exposes only the page, health and form submission routes. Protect source, assets, database and backups.\n\nPublic mode deliberately makes the exported page public. Do not enable it with private content. This backend is single-instance SQLite; it is not a scalable multi-tenant service. The limiter uses the socket IP (not spoofable forwarded headers); a proxy may share its 20 requests/minute quota across visitors. Configure a trusted ingress rate limit and bot protection before wider use. Establish consent, retention and backup policies for form data.\n\n## Boundaries\nIncluded: native pages, local interactions, embedded supported assets, validated contact forms and persistent submissions. External HTTPS media still requires its source. No passwords, login/accounts, payments, wallet, subscription engine, AI agents, provider generation or arbitrary application backend is included. VORLDA workshop source is not this customer application. data/ is runtime state, not a public static asset. Import limits: 16 MiB total embedded assets.\n\n## العربية\nهذه حزمة تطبيق VORLDA أصلي مع كود البناء وخادم لحفظ ردود النماذج، وليست نسخة من منصة VORLDA أو خادمًا عامًا لكل أنواع التطبيقات. افتح المجلد في أداة البرمجة، شغّل npm test ثم npm start. لإعادته للمحرر استورد project.vorlda.json. لا تنشر بيانات خاصة، ولا ترفع مجلد data إلى مجلد عام.\n`},
 ];
 return files;
}
export async function portableManifest(files:{name:string;content:string}[]){return JSON.stringify({format:'vorlda-native-source',version:1,runtime:'Node.js >=24',backend:'single-instance SQLite contact forms',files:await Promise.all(files.map(async f=>({path:f.name,sha256:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(f.content))),b=>b.toString(16).padStart(2,'0')).join('')})))},null,2);}
