import world from './world.ts?raw';
import compiler from './compiler.ts?raw';
import forms from './forms.ts?raw';
import projectIo from './project-io.ts?raw';
import build from '../portable/build.mjs.template?raw';
import server from '../portable/server.mjs.template?raw';
import responses from '../portable/responses.mjs.template?raw';
import instance from '../portable/instance.mjs.template?raw';
import adminAuth from '../portable/admin-auth.mjs.template?raw';
import adminOperator from '../portable/admin-operator.mjs.template?raw';
import adminHtml from '../portable/admin.html.template?raw';
import adminScript from '../portable/admin.js.template?raw';
export const portableSources={world,compiler,forms,projectIo,build,server,responses,instance,adminAuth,adminOperator,adminHtml,adminScript};
